name: eMOP Continuous Integration

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java-version: [ 8, 9, 10, 11, 12, 13, 14, 15 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: Install STARTS
      run: bash scripts/install-starts.sh
    - name: Verify with Maven
      run: mvn verify -B
